### ISSUE TITLE
Log spam if render distance is set below minimum

### ISSUE THREAD

**Issue by Ultimushadow** [Tre5et/adaptiveview#2]
Absolutely trivial issue but I figured I would let you know.
While testing my server side pack, I had set my view distance low (2) to load things a little faster. I happened to set it below the config's minimum view distance (4). When I looked at the logs, every tick resulted in a message of "Changing view distance to 2, from 4" until I changed it back.
As I said, one of the most harmless bugs possible, but log spam is one of my sworn enemies so any attempt to clean it up would be appreciated even for this stupidly minute use case. Perhaps disabling the mod from attempting to change the render distance in single player, and/or giving a warning message that the distance is below minimum when the mod checks the performance.

**Comment by Tre5et** [comment]
Thanks for reporting this.
I disabled the mod by default when running in a client environment now, which should prevent this behavior.
This change will be included in the next update.

**Comment by Ultimushadow** [comment]
Perfect solution, thanks for looking into it!
