### ISSUE TITLE
default config seems incorrect (or settings aren't explained well)

### ISSUE THREAD

**Issue by LucilleTea** [Tre5et/adaptiveview#3]
the default config file generated by the mod is this
```
{
  "locked": 0,
  "updateInterval": 600,
  "minMspt": 40,
  "maxMspt": 50,
  "minMsptAggressive": 60,
  "maxMsptAggressive": 30,
  "minViewDistance": 4,
  "maxViewDistance": 20,
  "overrideClient": false
}
```

the minMspt is lower than the maxMspt, but the minMsptAggressive is higher than the maxMsptAggressive.

i would think that when mspt is below the minimum, view distance increases, and when mspt is above the maximum, view distance decreases?
and the aggressive settings would do this more drastically? but the aggressive settings don't make sense for this, so how should it work?

**Comment by Tre5et** [comment]
This has finally been fixed with the config rework in v2.0.0. Sorry for the delay.
