### ISSUE TITLE
[Feature Request] Command to see current view distance

### ISSUE THREAD

**Issue by Discomanco** [Tre5et/adaptiveview#4]
Very simple request, a command to see what the current view distance is at, and maybe how long until next check.
Maybe a setting to announce to server ops when view distance changes, defaulted to off and only announces if it actually changes ofc

**Comment by Tre5et** [comment]
You can see the current view distance by simply running /adaptiveview. I might look into the announcement thing in the future.

**Comment by Discomanco** [comment]
Ah, I see.  
Not something that seems to be normal with most mods, or maybe I'm just getting old school. The base command would just give you a list of subcommands, rather than 'do' anything

**Comment by Tre5et** [comment]
I think it's rather common for commands to work like this. The vanilla /difficulty command for example displays the current difficulty. Similarly, carpet mod's /carpet shows the current settings.

Still something to think about, as it might not be obvious that this is an option.
It's staying like this for now though.

**Comment by Tre5et** [comment]
In v2.0.0 status commands were added to make it more obvious where to see the current view distance. A notification system has been implemented aswell.
