### ISSUE TITLE
[Feature Request] Option to give names to rules

### ISSUE THREAD

**Issue by NuzzasKatla** [Tre5et/adaptiveview#6]
Hi,
I'd like to request a feature where I can name the rules, so instead of this
![image](https://github.com/Tre5et/adaptiveview/assets/70723820/947ac255-2a78-4cb7-bd79-5d2b1cf34497)
it could say something like:
`
[AdaptiveView] Changed View Distance from 15 to 16 because of Rule: <custom name>
`
in the config, it could be an additional field in the rule section
```
{
  "type": "PLAYERS",
  "name": "<custom name>",
  "min": 4,
  "max_view_distance": 20
}
```

Thanks for reading.

**Comment by Tre5et** [comment]
Thanks for the suggestion and great timing!

This was added in v2.1.0.
