### ISSUE TITLE
Add support for simulation distance

### ISSUE THREAD

**Issue by Crendgrim** [Tre5et/adaptiveview#7]
It would be great if this mod would also support dynamically setting the simulation distance based on lag. In some cases I would expect that to have an even bigger impact on performance than the render distance.

**Comment by Tre5et** [comment]
Support for simulation distance was added in v2.3.0 (available for 1.20 and 1.21).

Note, simulation distance is always smaller or equal to the view distance, so adjusting simulation distance will never achieve a greater impact on performance than view distance. It can however provide a smoother experience to players that aren't using mods like Bobby.

**Comment by Crendgrim** [comment]
Thank you!
