### ISSUE TITLE
[Feature Request] Add the current simulation distance to the output of /adaptiveview status 

### ISSUE THREAD

**Issue by dive155** [Tre5et/adaptiveview#8]
First of all the mod is amazing, thank you for the great work!
As the title says, currently `/adaptiveview status` only shows the current view distance, while the current simulation distance is not shown.
On my server the view distance and the simulation distance are significantly different so the change would really help with optimization. It would be cool if we had this option.

**Comment by Tre5et** [comment]
Thanks for the suggestion! I've added this in v2.3.1 for version 1.21.4 or versions 1.20-1.21.3. Let me know if you have any other issues.
